Do not re-add floppy disk files to VMX
This commit fixes errors like this in the vsphere post-processor when using floppy files in the builder step:
Error: File (/var/folders/zl/57c1vmr532z_ryf1scw53_b9ycmxh7/T/packer964492999) could not be found

The configure VMX step re-adds the floppy files, so we need to configure the VMX and _then_ clean the VMX in that order.