Disable vendored plugins when PACKER_LEGACY_MODE is off
This change allows users to disable the loading of vendored plugins by setting legacy mode off.
In this mode Packer will rely only on plugins that have been installed via packer init or the packer plugins command.

```
// Running validate on JSON with Packer legacy mode unset; all plugins loaded by default
~>  go run . validate ../packer-templates/amazon-ebs/amazon-ebs_ubuntu_shell_manifest.json

Legacy JSON Configuration Mode enabled.
The template will be parsed in the legacy configuration style. Legacy style
templates will continue to work but users are encouraged to move HCL style templates.
templates will continue to work but users are encouraged to move to HCL style templates.
See: https://learn.hashicorp.com/tutorials/packer/hcl2-upgrade

In JSON mode automatic loading of vendored plugins is enabled by default.  In future
this feature will be removed and Packer will rely only on system installed plugins.
To disable automatic loading of vendored plugins set PACKER_LEGACY_MODE=off
See: https://packer.io/docs/templates/legacy-mode

The configuration is valid.

// Running validate on JSON with Packer legacy mode explicitly set to on; all plugins loded
~>  PACKER_LEGACY_MODE=on go run . validate ../packer-templates/amazon-ebs/amazon-ebs_ubuntu_shell_manifest.json
The configuration is valid.

// Running validate on JSON with Packer legacy mode explicitly set to off
~>  PACKER_LEGACY_MODE=off go run . validate ../packer-templates/amazon-ebs/amazon-ebs_ubuntu_shell_manifest.json

Legacy JSON Configuration Mode enabled.
The template will be parsed in the legacy configuration style. Legacy style
templates will continue to work but users are encouraged to move HCL style templates.
templates will continue to work but users are encouraged to move to HCL style templates.
See: https://learn.hashicorp.com/tutorials/packer/hcl2-upgrade

In JSON mode automatic loading of vendored plugins is enabled by default.  In future
this feature will be removed and Packer will rely only on system installed plugins.
To disable automatic loading of vendored plugins set PACKER_LEGACY_MODE=off
See: https://packer.io/docs/templates/legacy-mode

Error: Failed to initialize build "amazon-ebs"

error initializing builder 'amazon-ebs': Unknown builder amazon-ebs

exit status 1
```