Ignores appengine
The appengine imports cause govendor to fail since it's imported as
"appengine". We get failures like:

    Error: Package "appengine" not a go package or not in GOPATH.

If we ignore it, the issue goes away and we can still comple